### ISSUE TITLE
Searches everything possible instead of in the correct language using latest Zeal and Vscode

### ISSUE THREAD

**Issue by David-Else** [deerawan/vscode-dash#15]
Hello,

I am using the latest Zeal 0.40 and Vscode 1.16.1.

When I am editing in Javascript language, I put the cursor over a keyword,  for example var, and press ctrl-h , and this appears in the Zeal search box:

`javascript,jquery,jqueryui,jquerym,react,angularjs,backbone,marionette,meteor,sproutcore,moo,prototype,bootstrap,foundation,lodash,underscore,ember,sencha,extjs,titanium,knockout,zepto,yui,d3,svg,dojo,coffee,nodejs,express,grunt,mongoose,moment,require,awsjs,jasmine,sails,sinon,chai,html,css,cordova,phonegap,unity3d:var`

I want to only search in Javascript, it should say:

`javascript:var`

The instructions say:

> Pressing ctrl + h. It will search for current specific documentation depends on language.

Is this a massive bug, or am i making a simple mistake? Exact same thing in HTML as well as JS. Really hope this can be fixed, thanks!

**Comment by deerawan** [comment]
Hi @David-Else, thank you for your question. 

This is expected behaviour. Zeal follows Dash when searching in documentation. For javascript ( extension `.js`), it will try to look in documentation based on the `file type<>docset` mapping. The default docset mapping for javascript file type is like the one you put 

```
javascript,jquery,jqueryui,jquerym,react,angularjs,backbone,marionette,meteor,sproutcore,moo,prototype,bootstrap,foundation,lodash,underscore,ember,sencha,extjs,titanium,knockout,zepto,yui,d3,svg,dojo,coffee,nodejs,express,grunt,mongoose,moment,require,awsjs,jasmine,sails,sinon,chai,html,css,cordova,phonegap,unity3d
```
The mapping above based on the Dash author mapping here https://kapeli.com/dash_plugins

You can change this configuration if you want https://github.com/deerawan/vscode-dash#change-docset-configuration. 

Let me know if you have further question. 😃

**Comment by David-Else** [comment]
**Thanks!!**

I get it now, I just got rid of all that nonsense by adding:

`"dash.docset.javascript": [
        "javascript"
    ]`

to my Vscode setting.

Brilliant add-on, thanks for making it work with Linux's Zeal, much appreciated. :heart_eyes:

**Comment by deerawan** [comment]
@David-Else you're welcome 👍
