### ISSUE TITLE
Add action to search selection in the profile that is currently active in Dash

### ISSUE THREAD

**Issue by nikitavoloboev** [deerawan/vscode-dash#44]
RIght now using this action is annoying because by default searching JS in Dash will search over many useless things like Gulp, jQuery and more

![2018-10-10 at 13 43](https://user-images.githubusercontent.com/6391776/46734110-8c8ad380-cc92-11e8-96c1-834e3b0f0bbb.png)

I would like to instead it to search over my currently active profile:

![2018-10-10 at 13 44](https://user-images.githubusercontent.com/6391776/46734130-9b718600-cc92-11e8-89b4-86c8ac1f7899.png)

Which I change often.

Is this possible to do or it's something VS Code doesn't allow?

**Comment by deerawan** [comment]
Hi @nikitavoloboev, 

I'm truly sorry for that. Is your active profile the Default one? 

![image](https://user-images.githubusercontent.com/1243921/46736760-07201700-ccc4-11e8-9322-872d78cbf937.png)

For your case, we have some workarounds: 

1. If it is Default profile, you can trigger search in all docsets, default shortcut is `ctrl + alt + h`. 

2. Override the settings for `javascript` to search only for some specific docsets. 

NOTE: this key settings is in vscode-dash `2.0.0`
```
"dash.languageIdToDocsetMap": {
  ...,
  "javascript": [
    "javascript",
    "react",
    "typescript 
  ]
  ...
}
```
This may not be a robust solution because you said that you changed the docset in active profile often.

**Comment by nikitavoloboev** [comment]
> Is your active profile the Default one?

It isn't. I have many profiles.

![2018-10-10 at 14 51](https://user-images.githubusercontent.com/6391776/46737520-f8be0500-cc9b-11e8-90d5-e2a5a7654f61.png)

Will try your solution now. Thank you.

**Comment by deerawan** [comment]
@nikitavoloboev gotcha. 

Please try solution (1) by using `ctrl + alt + h`.  Hope it can solve your issue.

**Comment by nikitavoloboev** [comment]
Thank you. That hotkey does what I needed. 🎊
