### ISSUE TITLE
Add support for Arduino

### ISSUE THREAD

**Issue by deerawan** [deerawan/vscode-dash#62]
Arduino is now supported in vscode through language extension

marketplace extension
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

**Comment by akdir** [comment]
I would like to add Arduino Support for this extension @deerawan. So I already looked at it and it seems like VSCode sees Arduino .ino file as a .cpp file, because the output of the `vscode.window.activeEditor.document.languageId` is `cpp` for `ino` files. That means you can add Arduino support by adding `arduino` as a key to the value `cpp` in the `package.json` file. But adding a new key/value pair for arduino itself will not work, because VSCode sees Arduino files as cpp files. 

So should I just add it to the cpp value? I would like to hear from you @deerawan.

**Comment by deerawan** [comment]
Hi @akdir, just noticed your message. Thank you. 

Let me do some investigation.

**Comment by deerawan** [comment]
@akdir have you installed the extension https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino? This is in order to detect the language ID correctly.

**Comment by akdir** [comment]
> @akdir have you installed the extension https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino? This is in order to detect the language ID correctly.

@deerawan , Yes that is the first thing I did. That did not change the `vscode.window.activeEditor.document.languageId` output, it is still cpp for `ino` files. So I thought maybe VSCode sees ino files just as CPP files, because afterall the "programming language" Arduino is based on C/C++ but has some special functions to interact with Analog and Digital I/O.

**Comment by deerawan** [comment]
interesting, maybe we can do the alternative way by detecting the filename https://github.com/deerawan/vscode-dash#file-name-to-docset-matching
